eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8100

spring:
  application:
    name: Zuul-Server

zuul:
  #servlet-path: /
  routes:
    configApi:
      path: /configApi/**
      serviceId: config-server

    productApi:
      path: /productApi/**
      serviceId: product-service

    customerApi:
      path: /customer/**
      serviceId: customer-service

