eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8200

spring:
  application:
    name: Config-Client

  cloud:
    config:
     uri: http://localhost:8100

  profiles:
    active: dev
