eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

server:
  port: 8300

spring:
  application:
      name: config-server

  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared
          #search-locations: classpath:/shared

  profiles:
    active: native


