eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8300

spring:
  application:
      name: Config-Server

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

  profiles:
    active: native


